### ISSUE TITLE
Missing SmartWeave object values

### ISSUE THREAD

**Issue by cedriking** [fabianriewe/SmartWeaveTesting#1]
Hey @fabianriewe ,
I was testing out the project and it seems to be working fine for some basic contracts, but as soon as we want to interact with the transaction or the block, it stops working.

There seems to be missing a few of the features that SmartWeaveGlobal includes available here: https://github.com/ArweaveTeam/SmartWeave/blob/master/src/smartweave-global.ts

For example, there's nothing related to the transaction that is doing an input, and this is used on many contracts, can we have this added? I guess just giving it random values for the txid (but with the same hash rule and char length) might be enough? 🤔 Not sure, but at least for now that could work.

Thanks!

**Comment by fabianriewe** [comment]
Sure will add it 👍🏻

**Comment by fabianriewe** [comment]
Created a draft in #2. Please let me know what you think of this.

**Comment by cedriking** [comment]
That looks good @fabianriewe 🙌🏼 Thank you for doing this so quickly!

**Comment by fabianriewe** [comment]
Awesome. Merging #2 then
